### ISSUE TITLE
利用梯度下降更新w参数的时候代码有问题

### ISSUE THREAD

**Issue by ZiyiLiubird** [nndl/nndl-exercise-ans#1]
对于求出的梯度，我们应该除以样本数n，否则实际求出的结果是nan，因为这个时候的梯度向量不是单个样本的梯度向量了而是所有样本的梯度向量之和。
更正参考代码：
def Ngrad_func(w, x, y):
      n = x.shape[0]
      return np.dot(x.T, (y-np.dot(x, w)))/n

**Comment by JerrikEph** [comment]
@ZiyiLiubird 哪个文件？实际应用中作为一个通用计算库，一般忽略batch的存在。通常是在计算完loss后做loss平均达到平均梯度的目的。

**Comment by ZiyiLiubird** [comment]
抱歉忘了说文件名了。
exercise-linear_regression.ipynb

**Comment by ZiyiLiubird** [comment]
并且这个实例中画的图也是有问题的吧，不是演示线性回归嘛，拟合出的曲线是非线性的。
chap2_linear_regression/exercise-linear_regression.ipynb

**Comment by JerrikEph** [comment]
@ZiyiLiubird 加了核函数的

**Comment by ZiyiLiubird** [comment]
> @ZiyiLiubird 加了核函数的

好的谢谢，那行代码没看仔细.
我最开始说的梯度过大的问题在使用高斯核函数的时候的确没问题，可视化结果也是正确的。
但是如果在源代码的基础上将gaussian_basis_1换成identity_basis则无法正确求解，除以n以后就正常了。
